<td>
  {$cell.mnemonic}
  <dl>
    <dt>Opcode</dt>
    <dd>{$cell.bytes}</dd>
    <dt>Bytes</dt>
    <dd>{$cell.space}</dd>
    <dt>Cycles</dt>
    <dd>{$cell.cycles}</dd>
    <dd>{$cell.description}</dd>
  </dl>
</td>
